version: '1.0'
services:
  backend:
    build: saiberkeep-backend
    ports:
      - "32168:32168"
    volumes:
      - .:/backend
    depends_on:
      - db
  db:
    image: mongo
  client:
    build: saiberkeep-client
    ports:
      - "443:443"
    volumes:
      - .:/client
    depends_on:
      - backend
